name: Ansible Lint

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history so the base commit is available

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Get list of changed YAML files
      id: changed-files
      run: |
        files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}  ${{git rev-parse HEAD}} | grep -E '\.ya?ml$' || echo '')
        echo "files=$files" >> $GITHUB_ENV

    - name: Run ansible-lint
      if: env.files != ''
      uses: ansible/ansible-lint-action@v6
      with:
        targets: ${{ env.files }}
        override-deps: |
          ansible==7.7.0
          ansible-lint==6.19.0
