name: Ansible Lint

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history so the base commit is available

    - name: Print GITHUB_WORKSPACE
      run: |
        echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
      shell: bash

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Check if specified version of Ansible is installed
      id: check_ansible_version
      run: |
        ansible_version=$(ansible --version | head -n 1 | awk '{print $2}')
        if [ "$ansible_version" != "7.7.0" ]; then
          echo "::set-output name=ansible_not_installed::true"
        else
          echo "::set-output name=ansible_not_installed::false"
        fi
      shell: bash

    - name: Install Ansible and Ansible Lint if required version is not installed
      if: steps.check_ansible_version.outputs.ansible_not_installed == 'true'
      run: |
        echo "Installing required version of Ansible..."
        pip install ansible==7.7.0
        echo "Installed Ansible version $(ansible --version)"
        echo "Installing required version of Ansible Lint..."
        pip install ansible-lint==6.19.0
        echo "Installed Ansible Lint version $(ansible-lint --version)"
      shell: bash


    - name: Get list of changed YAML files
      id: changed_files
      run: |
        files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.ya?ml$' || echo '')
        echo $files
        files_list=$(echo $files | tr " " "\n")
        echo $files_list
        for file in $files_list; do
          echo "Linting $GITHUB_WORKSPACE/$file"
          if ! ansible-lint "$GITHUB_WORKSPACE/$file"; then
            echo "Linting of $GITHUB_WORKSPACE/$file failed"
          fi
        done
      shell: bash

   